/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning                                                                       \
    "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void GPIO_interrup_test(void);
void GPIO_intrrupt_handler(void);
void SPI_senddata_test(void);

#include <stdint.h>
#include <stm32f429.h>
// #include <GPIO_driver.h>

int main(void) {
    GPIO_interrup_test();
    SPI_senddata_test();
    for (;;)
        ;
}

void SPI_senddata_test(void) {
    GPIO_Handle_t SPIPins;

    SPIPins.pGPIOx = GPIOB;
    SPIPins.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
    SPIPins.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
    SPIPins.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    SPIPins.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
    SPIPins.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;

    // SCLK
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
    GPIO_Init(&SPIPins);

    // MOSI
    SPIPins.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_15;
    GPIO_Init(&SPIPins);

    SPI_Handle_t SPI2handle;

    SPI2handle.pSPIx = SPI2;
    SPI2handle.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
    SPI2handle.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
    SPI2handle.SPIConfig.SPI_SclkSpeed =
        SPI_SCLK_SPEED_DIV256; // generates sclk of 8MHz
    SPI2handle.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
    SPI2handle.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;
    SPI2handle.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
    SPI2handle.SPIConfig.SPI_SSM =
        SPI_SSM_EN; // software slave management enabled for NSS pin

    SPI_Init(&SPI2handle);

    char user_data[] = "Hello world";
    while (1) {
        SPI_SendData(SPI2, (uint8_t *)user_data, strlen(user_data));
    }
}

void GPIO_interrup_test(void) {
    // config PB0 as input interrupt
    GPIO_Handle_t gpio = {.GPIO_PinConfig = {.GPIO_PinNumber = GPIO_PIN_0,
                                             .GPIO_PinMode = GPIO_MODE_IT_FT,
                                             .GPIO_PinSpeed = GPIO_SPEED_FAST,
                                             .GPIO_PinPuPdControl = GPIO_PIN_PU,
                                             .GPIO_PinOPType = GPIO_OP_TYPE_PP,
                                             .GPIO_PinAltFunMode = 0},
                          .pGPIOx = GPIOB};

    GPIO_Init(&gpio);

    // config PG13 as output
    gpio.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_13;
    gpio.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    gpio.pGPIOx = GPIOG;

    GPIO_Init(&gpio);

    GPIO_WriteToOutputPin(GPIOG, GPIO_PIN_13, SET);
    // register interrupt handler
    // GPIO_RegisterIRQHandler(GPIO_PIN_0, 15, GPIO_intrrupt_handler);
}

void GPIO_intrrupt_handler(void) {
    GPIO_ToggleOutputPin(GPIOG, GPIO_PIN_13);
    GPIO_IRQHandling(GPIO_PIN_0);
}

void EXTI0_IRQHandler(void) { GPIO_intrrupt_handler(); }
